name: Multi-Environment Deploy
on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV_FILE=docker-compose.prod.yml" >> $GITHUB_ENV
          else
            echo "ENV_FILE=docker-compose.staging.yml" >> $GITHUB_ENV
          fi

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: pandoshar
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/fullstack-app
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            sudo docker compose up -d --build -f ${{ env.ENV_FILE }}
