name: Multi-Environment Deploy
on:
  push:
    branches: [main] # Этот воркфлоу следит ТОЛЬКО за main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: pandoshar
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/fullstack-app
            git config pull.rebase false
            git fetch origin
            git checkout main
            git pull origin main --no-rebase
            
            # Принудительно запускаем именно prod-файл с именем проекта production
            sudo ~/.docker/cli-plugins/docker-compose -p fullstack-production -f docker-compose.prod.yml up -d --build
